---
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: ghcr.io/kzmake/idempotency-key/api-gateway
      docker: { dockerfile: Dockerfile.golang, network: host, buildArgs: { SERVICE_NAME: api/gateway } }
    - image: ghcr.io/kzmake/idempotency-key/svc-time
      docker: { dockerfile: Dockerfile.golang, network: host, buildArgs: { SERVICE_NAME: svc/time } }
deploy:
  kustomize:
    paths:
      - manifests/overlays/localhost
profiles:
  - name: localhost
  - name: production
    deploy:
      kustomize:
        paths:
          - manifests/overlays/production
portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: default
    port: 8080
    localPort: 58080
  - resourceType: service
    resourceName: svc-time
    namespace: default
    port: 50051
    localPort: 50051
