---
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: ghcr.io/kzmake/idempotency-key/time-gateway
      docker:
        {
          dockerfile: Dockerfile.golang,
          network: host,
          buildArgs: { SERVICE_NAME: time/gateway },
        }
    - image: ghcr.io/kzmake/idempotency-key/time-service
      docker:
        {
          dockerfile: Dockerfile.golang,
          network: host,
          buildArgs: { SERVICE_NAME: time/service },
        }
deploy:
  kustomize:
    paths:
      - manifests/overlays/localhost
profiles:
  - name: localhost
  - name: production
    deploy:
      kustomize:
        paths:
          - manifests/overlays/production
portForward:
  - resourceType: service
    resourceName: time-gateway
    namespace: default
    port: 8080
    localPort: 58080
  - resourceType: service
    resourceName: time-service
    namespace: default
    port: 50051
    localPort: 50051
